### PR TITLE
Stories design

### PR DESCRIPTION
**Pull request by wrightmartin**

### CODE REVIEW

**Comment by jdrever** [comment]
Hi Martin,

Getting an error when Netlify tries to build this branch:

Failed during stage 'deploying site': Invalid filename 'images/door [#45].svg'. Deployed filenames cannot contain # or ? characters

Any ideas?  Not sure why the #45 is getting added

Not super urgent, as can show to the partners this morning by running locally.

James.

**Comment by wrightmartin** [comment]
This had me completely stumped but I've figured it out. The images very briefly had the numbers and characters in the filename and the site detected them and built them. When I renamed them it didn't remove the odd filenames. I didn't think to check the `_site` folder. Will be fixed in the next commit

**Comment by wrightmartin** [comment]
@jdrever lots fixed in here now, I've also updated develop to be in sync with master

**Comment by jdrever** [comment]
Great thanks Martin, will take a look next week! Have a good weekend 😊

**Pull request merged**
